name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "${{ secrets.DOCKER_USERNAME }}"/certification-app-frontend:latest
    - name: Push image to Docker Registry
      run: docker push "${{ secrets.DOCKER_USERNAME }}"/ertification-app-frontend:latest